### PR TITLE
Fixed blank rows at end of paged grid

### LINKED ISSUE #64: Blank rows at the end of grid when paging enabled
Example:

1. See CodePen below
2. Go to last page
3. Move cursor over space below last row

http://codepen.io/bensgroi/pen/zNqyKb

### PR DESCRIPTION
**Pull request by bensgroi**
Resolved #64.
Fixed some formatting on the readme.
Added a few more unit tests.

### CODE REVIEW

File: src/components/body/BodyController.js [hunk 1]
```diff
@@ -80,7 +80,9 @@ export default class BodyController {
     this.tempRows.splice(0, this.tempRows.length);
 
     for (i = 0; i < this.options.paging.size; i += 1) {
-      this.tempRows[i] = this.rows[(this.options.paging.offset * this.options.paging.size) + i];
+      if (typeof this.rows[(this.options.paging.offset * this.options.paging.size) + i] !== 'undefined') {
```
Comment (bensgroi) [inline src/components/body/BodyController.js]: What kind of amateur wrote this function?? 🥇

File: demos/paging.html [hunk 2]
```diff
@@ -76,7 +76,8 @@
             ],
             columnMode: 'force',
             paging: {
-              mode: 'internal'
+              mode: 'internal',
+              size: 12
```
Comment (jonshaffer) [inline demos/paging.html]: this was 10 previously, why the change?

File: src/components/DataTableController.spec.js [hunk 3]
```diff
@@ -36,14 +36,54 @@ describe('DataTableController', () => {
...
+        reorderable: true,
+        rowHeight: 30,
+        scrollbarV: true,
+        selectable: false,
+        sortable: true,
+        sortType: 'multiple',
+      };
+
+      let options = ctrl.options;
+      delete options.$outer;
```
Comment (jonshaffer) [inline src/components/DataTableController.spec.js]: you should probably modify this off of an angular.copy of ctrl.options to avoid any unexpected issues

File: src/components/DataTableController.spec.js [hunk 4]
```diff
@@ -105,174 +145,174 @@ describe('DataTableController', () => {
...
+          cellRenderer: undefined,
+          cellDataGetter: undefined,
+          group: false,
+          isTreeColumn: false,
+          isCheckboxColumn: false,
+          headerCheckbox: false,
+          canAutoResize: true
+        });
+        col = ctrl.options.columns[1];
+        delete col.$id;
```
Comment (jonshaffer) [inline src/components/DataTableController.spec.js]: same as above

File: src/components/DataTableController.spec.js (hunk 3 above)
Comment (bensgroi) [inline src/components/DataTableController.spec.js]: Fair enough

File: demos/paging.html (hunk 2 above)
Comment (bensgroi) [inline demos/paging.html]: Went to 12 because the data source is 100 rows and I wanted to verify that everything looks good with a row count not evenly divisible by the page size.

File: src/components/DataTableController.spec.js (hunk 3 above)
Comment (bensgroi) [inline src/components/DataTableController.spec.js]: Oh right, you can't use angular.copy on an object that contains Scope instances. I don't think this should cause problems anyway.

File: src/components/DataTableController.spec.js [hunk 5]
```diff
@@ -36,24 +36,52 @@ describe('DataTableController', () => {
...
+        scrollbarV: true,
+        selectable: false,
+        sortable: true,
+        sortType: 'multiple',
+      };
 
-    it('should have paging.mode: null', () => {
-      expect(ctrl.options.paging.mode).toBeNull();
-    });
+      let options = ctrl.options;
```
Comment (adlaird) [inline src/components/DataTableController.spec.js]: do these 2 lines belong inside of a before/after each function?

File: demos/paging.html (hunk 2 above)
Comment (jonshaffer) [inline demos/paging.html]: thanks, didn't realize this was only in demos

File: src/dataTable.js [hunk 6]
```diff
@@ -30,7 +30,7 @@ export default angular
   .directive('dtHeaderCell', HeaderCellDirective)
   .directive('dtBody', BodyDirective)
   .directive('dtScroller', ScrollerDirective)
-  .directive('dtSeletion', SelectionDirective)
```
Comment (jonshaffer) [inline src/dataTable.js]: !! +1
